server:
  port: 8087
  error:
    include-stacktrace: on-param
    
spring:
  application:
    name: springboot2-essentials
  datasource:
    url: jdbc:mysql://localhost:3307/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
        
info:
  app: Spring Boot 2 Essentials By DevDojo
  website: http://devdojo.academy
  
          